export const appRoutes = {
	home: '/',
	login: '/login',
	signUp: '/signup',
	application: '/applications',
	addApplication: '/applications/add',
	updateApplication: '/applications/update',
	viewApplication: '/applications/view',
	interviewQuestions: '/interview-questions',
	addInterviewQuestions: '/interview-questions/add',
	updateInterviewQuestions: '/interview-questions/update',
	faq: '/faq',
	pricing: '/pricing',
	aboutUs: '/about-us',
	contactUs: '/contact-us',
	privacyPolicy: '/privacy-policy',
	termsOfService: '/terms-of-service',
};
